# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Caesar < Formula
  desc ""
  homepage "https://github.com/simonmittag/caesarcipher"
  version "0.2.1"

  on_macos do
    url "https://github.com/simonmittag/caesarcipher/releases/download/v0.2.1/caesarcipher_0.2.1_darwin_all.tar.gz"
    sha256 "ee02365b622fc0f28a39654905176453758c8f50034943d0b24ad0d728bab859"

    def install
      bin.install "caesar"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/simonmittag/caesarcipher/releases/download/v0.2.1/caesarcipher_0.2.1_linux_amd64.tar.gz"
        sha256 "118a953e24ec8280098cdde244de542c2ca107d76a0c93b978bfa61e27c65119"

        def install
          bin.install "caesar"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/simonmittag/caesarcipher/releases/download/v0.2.1/caesarcipher_0.2.1_linux_arm64.tar.gz"
        sha256 "df156800cd7047f84e1cfd6205dda814479bffb3df7457cb223a09f858b58cc7"

        def install
          bin.install "caesar"
        end
      end
    end
  end
end
