# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Caesar < Formula
  desc ""
  homepage "https://github.com/simonmittag/caesarcipher"
  version "0.2.0"

  on_macos do
    url "https://github.com/simonmittag/caesarcipher/releases/download/v0.2.0/caesarcipher_0.2.0_darwin_all.tar.gz"
    sha256 "794c75df79c58b85463ce2a07bb242bf956e34166358980fc2f2a5841c11dafa"

    def install
      bin.install "caesarcipher"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/simonmittag/caesarcipher/releases/download/v0.2.0/caesarcipher_0.2.0_linux_amd64.tar.gz"
        sha256 "6d9ba607e9925a5087e62a1f9ebccacb8fb003923acd2a2970ae964e6301f826"

        def install
          bin.install "caesar"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/simonmittag/caesarcipher/releases/download/v0.2.0/caesarcipher_0.2.0_linux_arm64.tar.gz"
        sha256 "2cbde2048537ce3a4a506f65c6a0e0bb73492b1e810a5c875cb251058283b70b"

        def install
          bin.install "caesar"
        end
      end
    end
  end
end
