# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Caesar < Formula
  desc ""
  homepage "https://github.com/simonmittag/caesarcipher"
  version "0.2.0"

  on_macos do
    url "https://github.com/simonmittag/caesarcipher/releases/download/v0.2.0/caesarcipher_0.2.0_darwin_all.tar.gz"
    sha256 "7312b3dcb73cd65fa140c1cf58cd96abcd9e29b0595dd64e5459262dc8667c8f"

    def install
      bin.install "caesar"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/simonmittag/caesarcipher/releases/download/v0.2.0/caesarcipher_0.2.0_linux_amd64.tar.gz"
        sha256 "9c7dacbae6df7d0004716c57a7c7b2df2712a4a4bfbbed6892439b74ea1ab451"

        def install
          bin.install "caesar"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/simonmittag/caesarcipher/releases/download/v0.2.0/caesarcipher_0.2.0_linux_arm64.tar.gz"
        sha256 "f8c38a0fbdef59d48c92b201d9af70bf1212e7dd1192de539a295629fb6db0b0"

        def install
          bin.install "caesar"
        end
      end
    end
  end
end
