# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GhPrSummarizer < Formula
  desc "Opinionated CLI utility to generate pull request summaries"
  homepage "https://github.com/simonmittag/gh-pr-summarizer"
  version "0.1.3"
  license "Apache-2.0"

  on_macos do
    url "https://github.com/simonmittag/gh-pr-summarizer/releases/download/v0.1.3/gh-pr-summarizer_0.1.3_darwin_all.tar.gz"
    sha256 "7f02849e82d591b8133c95d71b82264425535b5aab7f46fbf0e0a8d1187cc709"

    define_method(:install) do
      bin.install "gh-pr-summarizer"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/simonmittag/gh-pr-summarizer/releases/download/v0.1.3/gh-pr-summarizer_0.1.3_linux_amd64.tar.gz"
      sha256 "87328747b3f26b3ebb55f5624ffb5cc22c3c06541fabae728d459323b8627e61"
      define_method(:install) do
        bin.install "gh-pr-summarizer"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/simonmittag/gh-pr-summarizer/releases/download/v0.1.3/gh-pr-summarizer_0.1.3_linux_arm64.tar.gz"
      sha256 "91441efad0fecbf55f5d37f22aa4b3d98007f16609abe4a156f8665026593f20"
      define_method(:install) do
        bin.install "gh-pr-summarizer"
      end
    end
  end
end
