# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GhPrSummarizer < Formula
  desc "Opinionated CLI utility to generate pull request summaries"
  homepage "https://github.com/simonmittag/gh-pr-summarizer"
  version "0.1.1"
  license "Apache-2.0"

  on_macos do
    url "https://github.com/simonmittag/gh-pr-summarizer/releases/download/v0.1.1/gh-pr-summarizer_0.1.1_darwin_all.tar.gz"
    sha256 "bcc44423c644eb791a88aa0e8bd66fc6627d670ad28ee05da6c0010d6f8ea189"

    define_method(:install) do
      bin.install "gh-pr-summarizer"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/simonmittag/gh-pr-summarizer/releases/download/v0.1.1/gh-pr-summarizer_0.1.1_linux_amd64.tar.gz"
      sha256 "3b911b7f5c53fe4d2d317dbaf762f6804f8ff0f31d2b5bc0af417938e4e84bdb"
      define_method(:install) do
        bin.install "gh-pr-summarizer"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/simonmittag/gh-pr-summarizer/releases/download/v0.1.1/gh-pr-summarizer_0.1.1_linux_arm64.tar.gz"
      sha256 "d5e6a32986c9be8f50c36709015dddf0a9821e09ed2d836be1f62782585d24ca"
      define_method(:install) do
        bin.install "gh-pr-summarizer"
      end
    end
  end
end
