# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class J8a < Formula
  desc ""
  homepage "https://github.com/simonmittag/j8a"
  version "0.9.4"

  on_macos do
    url "https://github.com/simonmittag/j8a/releases/download/v0.9.4/j8a_0.9.4_darwin_all.tar.gz"
    sha256 "f34de9d2aa0424c93bda3d547d40e2cd47d9239164fe12441d1701cc613b79e3"

    def install
      bin.install "j8a"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/simonmittag/j8a/releases/download/v0.9.4/j8a_0.9.4_linux_arm64.tar.gz"
      sha256 "f5c2246e32f51a08db49d62dc3a571d766074d0733d00fcb94d8cf721510d4ea"

      def install
        bin.install "j8a"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/simonmittag/j8a/releases/download/v0.9.4/j8a_0.9.4_linux_amd64.tar.gz"
      sha256 "3632eaf48f15d78344df08d2faa20373b6d4cf76072bbaa88626849a9bdfcaec"

      def install
        bin.install "j8a"
      end
    end
  end
end
