# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class L0la < Formula
  desc ""
  homepage "https://github.com/simonmittag/l0la"
  version "0.1.1"
  depends_on :macos

  on_macos do
    url "https://github.com/simonmittag/l0la/releases/download/v0.1.1/l0la_0.1.1_darwin_all.tar.gz"
    sha256 "fa0ac2840967bb84546609ff677f2efa3acef6e05e998614edf48a20c2d382af"

    def install
      bin.install "l0la"
    end
  end
end
