# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class L0la < Formula
  desc ""
  homepage "https://github.com/simonmittag/l0la"
  version "0.1.2"
  depends_on :macos

  on_macos do
    url "https://github.com/simonmittag/l0la/releases/download/v0.1.2/l0la_0.1.2_darwin_all.tar.gz"
    sha256 "107e11da027f589a3f2f84c62c42eade7c236cbbe5e4ef457a03fd141ac204da"

    def install
      bin.install "l0la"
    end
  end
end
