# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mse6 < Formula
  desc ""
  homepage "https://github.com/simonmittag/mse6"
  version "0.5.1"

  on_macos do
    url "https://github.com/simonmittag/mse6/releases/download/v0.5.1/mse6_0.5.1_darwin_all.tar.gz"
    sha256 "e1600eb0dd38e49029208d52d2740c7559c0c3ee4e29b09719ec76884c8fdfc0"

    def install
      bin.install "mse6"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/simonmittag/mse6/releases/download/v0.5.1/mse6_0.5.1_linux_arm64.tar.gz"
      sha256 "cad44a4d5551f083045a3e4e8685a3eaf40e715ca6cf0a59a8f73d4efd5a7644"

      def install
        bin.install "mse6"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/simonmittag/mse6/releases/download/v0.5.1/mse6_0.5.1_linux_amd64.tar.gz"
      sha256 "776b5fc4fdd45cb3cfe140285bea4ec5c4199595d9d4abe9384c9b59fc5e9c54"

      def install
        bin.install "mse6"
      end
    end
  end
end
