# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mse6 < Formula
  desc ""
  homepage "https://github.com/simonmittag/mse6"
  version "0.4.7"

  on_macos do
    url "https://github.com/simonmittag/mse6/releases/download/v0.4.7/mse6_0.4.7_darwin_all.tar.gz"
    sha256 "31ba738acbc06a82c12dec5c00618846b57c1b79569eec9d050c2acb2b5918a1"

    def install
      bin.install "mse6"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/simonmittag/mse6/releases/download/v0.4.7/mse6_0.4.7_linux_arm64.tar.gz"
      sha256 "d21ef29b836e998bf0df81c3b71c7c5a3895345bebe7fb922c5b66e43d50f960"

      def install
        bin.install "mse6"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/simonmittag/mse6/releases/download/v0.4.7/mse6_0.4.7_linux_amd64.tar.gz"
      sha256 "4d4dcd4bb52317523de64f34dc2916c0c8608e25151b8b25d786346aed0d23e0"

      def install
        bin.install "mse6"
      end
    end
  end
end
