# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mse6 < Formula
  desc ""
  homepage "https://github.com/simonmittag/mse6"
  version "0.4.9"

  on_macos do
    url "https://github.com/simonmittag/mse6/releases/download/v0.4.9/mse6_0.4.9_darwin_all.tar.gz"
    sha256 "0e1cc34323181b78479aa20e39a77b3c8ed805e0197caf977c63af35c85dfaf1"

    def install
      bin.install "mse6"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/simonmittag/mse6/releases/download/v0.4.9/mse6_0.4.9_linux_amd64.tar.gz"
      sha256 "b696644e092fa73bf3871c4eabf43368825a7affcbea094d567ff0e0463691e3"

      def install
        bin.install "mse6"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/simonmittag/mse6/releases/download/v0.4.9/mse6_0.4.9_linux_arm64.tar.gz"
      sha256 "f1a3acf27f8c208542964dd352a5c9919e9de82ecbf0ea6289a84739f487a53b"

      def install
        bin.install "mse6"
      end
    end
  end
end
