# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class P0d < Formula
  desc ""
  homepage "https://github.com/simonmittag/j8a"
  version "0.9.2"

  on_macos do
    url "https://github.com/simonmittag/j8a/releases/download/v0.9.2/j8a_0.9.2_darwin_all.tar.gz"
    sha256 "e6d27cfa61febd43f0ca07f8f029af8086e52086c82fae0f5fe2ec2c46835944"

    def install
      bin.install "j8a"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/simonmittag/j8a/releases/download/v0.9.2/j8a_0.9.2_linux_arm64.tar.gz"
      sha256 "75fb219e22d17be8525558d3271c2f3378e6cd66bf619fd83f37d058d5bd96eb"

      def install
        bin.install "j8a"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/simonmittag/j8a/releases/download/v0.9.2/j8a_0.9.2_linux_amd64.tar.gz"
      sha256 "c0133ad8dc668da3f11198faf578c4f7c98fd6b85281fa89f09c429b6bbe11dd"

      def install
        bin.install "j8a"
      end
    end
  end
end
