# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class P0d < Formula
  desc ""
  homepage "https://github.com/simonmittag/p0d"
  version "0.3.8"

  on_macos do
    url "https://github.com/simonmittag/p0d/releases/download/v0.3.8/p0d_0.3.8_darwin_all.tar.gz"
    sha256 "66eae9378475810d1edb21855d9eff15d4e36a58125377055baabac9470a44f9"

    def install
      bin.install "p0d"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/simonmittag/p0d/releases/download/v0.3.8/p0d_0.3.8_linux_arm64.tar.gz"
      sha256 "fb5fa1fce5f96f0670f08048a86f0c29576fc4541436460294719b303721f520"

      def install
        bin.install "p0d"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/simonmittag/p0d/releases/download/v0.3.8/p0d_0.3.8_linux_amd64.tar.gz"
      sha256 "6353fe534987f25ce058d7b6ff6b3b622a6206fa994f5ba2c351297c57be0040"

      def install
        bin.install "p0d"
      end
    end
  end
end
