# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Punycoder < Formula
  desc ""
  homepage "https://github.com/simonmittag/punycoder"
  version "0.0.11"

  on_macos do
    url "https://github.com/simonmittag/punycoder/releases/download/v0.0.11/punycoder_0.0.11_darwin_all.tar.gz"
    sha256 "e0ba93397f8cf7711c3751f9d4cecc120b576966412af892899e424081b31aed"

    def install
      bin.install "punycoder"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/simonmittag/punycoder/releases/download/v0.0.11/punycoder_0.0.11_linux_arm64.tar.gz"
      sha256 "67db1f38ef6915b1320fd143d3878e298f9babb568d52c24289affaa9b593b11"

      def install
        bin.install "pwt"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/simonmittag/punycoder/releases/download/v0.0.11/punycoder_0.0.11_linux_amd64.tar.gz"
      sha256 "b874b56beab5ecaba24348ee430edd260210f0d07315cbe2d621b663d6ed7479"

      def install
        bin.install "pwt"
      end
    end
  end
end
