# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Punycoder < Formula
  desc ""
  homepage "https://github.com/simonmittag/punycoder"
  version "0.0.9"

  on_macos do
    url "https://github.com/simonmittag/punycoder/releases/download/v0.0.9/punycoder_0.0.9_darwin_all.tar.gz"
    sha256 "de951bd2fc4e0a6cd5c5c456378ded50d5d6834778359bd79a75c8b885d4437a"

    def install
      bin.install "punycoder"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/simonmittag/punycoder/releases/download/v0.0.9/punycoder_0.0.9_linux_arm64.tar.gz"
      sha256 "bb1275f4ef9d44b6b9a429afa3b015f900c47d68d1940c6e352a1c3a24219a38"

      def install
        bin.install "pwt"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/simonmittag/punycoder/releases/download/v0.0.9/punycoder_0.0.9_linux_amd64.tar.gz"
      sha256 "dfb82d18ad8ffd4408c415e9f23de3a6a4a4b9ec36103576a28ae089f8a02b45"

      def install
        bin.install "pwt"
      end
    end
  end
end
