# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Punycoder < Formula
  desc ""
  homepage "https://github.com/simonmittag/punycoder"
  version "0.2.2"

  on_macos do
    url "https://github.com/simonmittag/punycoder/releases/download/v0.2.2/punycoder_0.2.2_darwin_all.tar.gz"
    sha256 "f709e9b73f378d068a129bc1ac32133f8be503bea9904251904a8ed48071fecf"

    def install
      bin.install "punycoder"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/simonmittag/punycoder/releases/download/v0.2.2/punycoder_0.2.2_linux_amd64.tar.gz"
      sha256 "aaa7101f76a86706bd2dfa1d512b2c721bd56a2b1604fe4cf48ba277a76a7d1a"

      def install
        bin.install "pwt"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/simonmittag/punycoder/releases/download/v0.2.2/punycoder_0.2.2_linux_arm64.tar.gz"
      sha256 "82edf6f4b5d098b7152637d4628773942ca4ba13433aa81dee87baf53f93809f"

      def install
        bin.install "pwt"
      end
    end
  end
end
