# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Puri < Formula
  desc ""
  homepage "https://github.com/simonmittag/puri"
  version "0.1.4"

  on_macos do
    url "https://github.com/simonmittag/puri/releases/download/v0.1.4/puri_0.1.4_darwin_all.tar.gz"
    sha256 "5b0a4f66b6ca3ffae72439b36a73e5b34ddf84388effdf8342625143e5692c18"

    def install
      bin.install "puri"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/simonmittag/puri/releases/download/v0.1.4/puri_0.1.4_linux_amd64.tar.gz"
      sha256 "4469acf5a802e5e72115f84b9e6a6b1996df34b487705b39db5b70510847f190"

      def install
        bin.install "puri"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/simonmittag/puri/releases/download/v0.1.4/puri_0.1.4_linux_arm64.tar.gz"
      sha256 "70e917f95610d0d8466ad862bc09dc4a5e1ebfedffbbdbe185a6a20190102bf6"

      def install
        bin.install "puri"
      end
    end
  end
end
