# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Puri < Formula
  desc ""
  homepage "https://github.com/simonmittag/puri"
  version "0.1.3"

  on_macos do
    url "https://github.com/simonmittag/puri/releases/download/v0.1.3/puri_0.1.3_darwin_all.tar.gz"
    sha256 "4c1ff14d469d00b99a7f16e12f072621993efc04ba3dc39dc9ef90ef157d224a"

    def install
      bin.install "puri"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/simonmittag/puri/releases/download/v0.1.3/puri_0.1.3_linux_amd64.tar.gz"
      sha256 "fbf9e2722ecc6f0cc0181ec18c9581c16cf43342593b2c6499a37b0108b1d93a"

      def install
        bin.install "puri"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/simonmittag/puri/releases/download/v0.1.3/puri_0.1.3_linux_arm64.tar.gz"
      sha256 "42551ce99514dcfefa55b3ef0c253b6d670bb15c18d7360149bc48769f3653a1"

      def install
        bin.install "puri"
      end
    end
  end
end
