# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pwt < Formula
  desc ""
  homepage "https://github.com/simonmittag/pwt"
  version "0.1.7"

  on_macos do
    url "https://github.com/simonmittag/pwt/releases/download/v0.1.7/pwt_0.1.7_darwin_all.tar.gz"
    sha256 "a454b16c6f2c8699800a8846c2f9f19cc70599519f7c5f4e469959d74f9c26a3"

    def install
      bin.install "pwt"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/simonmittag/pwt/releases/download/v0.1.7/pwt_0.1.7_linux_arm64.tar.gz"
      sha256 "07d41a2b8a58153a02ec184615cd01ff0a338f817207fb92b16a9a58627cf227"

      def install
        bin.install "pwt"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/simonmittag/pwt/releases/download/v0.1.7/pwt_0.1.7_linux_amd64.tar.gz"
      sha256 "ba76c5ef3ff5cb88b2d076b3fa5368ad6c008be570dcd990f7b2971193bf5c17"

      def install
        bin.install "pwt"
      end
    end
  end
end
