# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pwt < Formula
  desc ""
  homepage "https://github.com/simonmittag/pwt"
  version "0.1.4"

  on_macos do
    url "https://github.com/simonmittag/pwt/releases/download/v0.1.4/pwt_0.1.4_darwin_all.tar.gz"
    sha256 "0d6dbc22093bbde71e3c7c4a879e9de5c78863352839314c46679a6a3274d32b"

    def install
      bin.install "pwt"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/simonmittag/pwt/releases/download/v0.1.4/pwt_0.1.4_linux_arm64.tar.gz"
      sha256 "df317675a36484462bfd37cd6346e0d7d754dd45d4f55e6b2a59a0f5dde069cf"

      def install
        bin.install "pwt"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/simonmittag/pwt/releases/download/v0.1.4/pwt_0.1.4_linux_amd64.tar.gz"
      sha256 "c5134375d55763a69ad1cdfa1a8b1ec6bd7babda1d58c9eaa84e7e43a5e3416e"

      def install
        bin.install "pwt"
      end
    end
  end
end
