# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pwt < Formula
  desc ""
  homepage "https://github.com/simonmittag/pwt"
  version "0.1.6"

  on_macos do
    url "https://github.com/simonmittag/pwt/releases/download/v0.1.6/pwt_0.1.6_darwin_all.tar.gz"
    sha256 "68349b601fb9d218165ac62b0a208402f5cc7aad4ec51a0a4d1f64fabd628b1c"

    def install
      bin.install "pwt"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/simonmittag/pwt/releases/download/v0.1.6/pwt_0.1.6_linux_amd64.tar.gz"
      sha256 "845940d4cbf8c3787390a7792894a7b27702b22ec1beabf273226de24b11d660"

      def install
        bin.install "pwt"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/simonmittag/pwt/releases/download/v0.1.6/pwt_0.1.6_linux_arm64.tar.gz"
      sha256 "084fbdd1f5083c7112969ad5af081770a917f5a3edc3aa9c31c32783a86b0b73"

      def install
        bin.install "pwt"
      end
    end
  end
end
