# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Vigenere < Formula
  desc ""
  homepage "https://github.com/simonmittag/vigenerecipher"
  version "0.1.1"

  on_macos do
    url "https://github.com/simonmittag/vigenerecipher/releases/download/v0.1.1/vigenerecipher_0.1.1_darwin_all.tar.gz"
    sha256 "5c3b021fcf99f3d3dc8abdce688336f11854240537e4bf80ef82d991a77109d3"

    def install
      bin.install "vigenere"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/simonmittag/vigenerecipher/releases/download/v0.1.1/vigenerecipher_0.1.1_linux_amd64.tar.gz"
        sha256 "07c3412da11d70ca4637e1e22475ef0de74c47651802469f1deb2c80f75cdf8b"

        def install
          bin.install "vigenere"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/simonmittag/vigenerecipher/releases/download/v0.1.1/vigenerecipher_0.1.1_linux_arm64.tar.gz"
        sha256 "193eb065d4ffaf4a6a0bf64b58c62015dcb15f60013b9d0c2b56753dcc35c31b"

        def install
          bin.install "vigenere"
        end
      end
    end
  end
end
